// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3SxAoDYxy9KxaF5T_jnfDypByL4rFEMw',
    appId: '1:133980924089:web:4fcd8847093c746497d368',
    messagingSenderId: '133980924089',
    projectId: 'ofran-7a7c5',
    authDomain: 'ofran-7a7c5.firebaseapp.com',
    storageBucket: 'ofran-7a7c5.firebasestorage.app',
    measurementId: 'G-6KNRHZH5WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX64fmSTWLbbtUUiw_gttfVDpET0sqHz0',
    appId: '1:133980924089:android:204f33224b8b9bfe97d368',
    messagingSenderId: '133980924089',
    projectId: 'ofran-7a7c5',
    storageBucket: 'ofran-7a7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QHVCu7_Hhz6A1x_nb7quwlm7ODaaBSc',
    appId: '1:133980924089:ios:627623a6f9dfb9ff97d368',
    messagingSenderId: '133980924089',
    projectId: 'ofran-7a7c5',
    storageBucket: 'ofran-7a7c5.firebasestorage.app',
    iosBundleId: 'com.a3traf.a3traf',
  );
}
